/*
 * File: app/model/MyModel1.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.MyModel1', {
    extend: 'Ext.data.Model',

    proxy: {
        type: 'ajax',
        url: 'http://localhost/inicioImg/generated.json',
        reader: {
            type: 'json',
            root: 'result'
        }
    },

    fields: [
        {
            name: 'name',
            type: 'string'
        },
        {
            name: 'company',
            type: 'string'
        }
    ]
});